require: rubocop-rails

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'Rakefile'

Style/StringLiterals:
  Exclude:
    - 'config/puma.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/ExtraSpacing:
  AllowForAlignment: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Rails:
  Enabled: true
