name: Test

on: push

env:
  RUBY_VERSION: 2.5.1
  RAILS_ENV: test

jobs:
  test-ruby:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:5.0.9
        ports:
        - 6379
    steps:
    - name: Start mysql server
      run: |
        sudo systemctl start mysql.service
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Rspec
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: root
        DB_PORT: 3306
        DOMAIN: http://localhost:3000
        MAILER_SENDER_ADDRESS: noreply@example.com
        AWS_REGION: ap-northeast-1
        REDIS_URL: 'redis://127.0.0.1:${{ job.services.redis.ports[6379] }}'
        REDIS_ENDPOINT: '127.0.0.1:${{ job.services.redis.ports[6379] }}'
      run: |
        bundle exec rake db:create db:test:prepare
        bundle exec rspec
    - name: Rubocop
      run: |
        bundle exec rubocop
    - name: Brakeman
      run: |
        bundle exec brakeman
